sonar.projectKey=ottbackendv01
sonar.projectName=ottbackendv01
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
